### ISSUE TITLE
Add Footer logo in all pages 

### ISSUE THREAD

**Issue by jaiyankargupta** [Mohak1809/OCD-Website#308]
**Add Footer logo in all pages**

**Comment by Agrawal-Vansh** [comment]
@jaiyankargupta  I think the issue is already resolved in latest branch(I think deployment link needs to be updated)

https://github.com/user-attachments/assets/782c0b6b-41c5-48b7-ba74-00d2f7ceddcb

**Comment by NikhilByteSmith** [comment]
the issue is still there even locally on my machine on the latest branch on the resources ,events and links page
![image](https://github.com/user-attachments/assets/2fb63b6c-ae73-4b04-9234-7c3b6afc1fa6)
it is like this

**Comment by Agrawal-Vansh** [comment]
@jaiyankargupta  Assign this issue to me I think the links are again needed to be updated must be overwritten in some commit on linkcorrection branch  and the logo also

**Comment by jaiyankargupta** [comment]
@Agrawal-Vansh done
